name: alignpaper
channels:
  - defaults
dependencies:
  - selenium
  - numpy
  - jupyter
  - pandas
  - nltk
  - altair
  - matplotlib
  - scikit-learn
  - gensim
  - tensorflow
  - tensorflow-hub
  - conda-forge::fastcluster
  - conda-forge::altair_saver
  - jupyterlab
  - yaml
  - pyyaml
  - pillow
  - torchvision
